name: Preprocess Dataset

on:
  push:
    paths:
      - "Preprocessing/automate_Verzha-Mahardika.py"
      - "namadataset_raw/Supplement-Sales-Weekly-Expanded_raw.csv"
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
         python Preprocessing/automate_Verzha-Mahardika.py

    - name: Cek hasil preprocessing
      run: |
        echo "Daftar isi direktori:"
        ls -R
        echo "Isi file hasil Preprocessing:"
        cat Preprocessing/Supplement-Sales-Weekly-Expanded_preprocessing.csv

    - name: Upload Hasil Preprocessing
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: Preprocessing/Supplement-Sales-Weekly-Expanded_preprocessing.csv
  
    - name: Commit dan Push file hasil preprocessing ke repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Preprocessing/Supplement-Sales-Weekly-Expanded_preprocessing.csv
        # ✅ Cek apakah ada perubahan sebelum commit
        if git diff --cached --quiet; then
          echo "✅ Tidak ada perubahan, tidak perlu commit"
        else
          git commit -m "Update hasil preprocessing otomatis"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
